### ISSUE TITLE
STOP ADDING FAMOUS DEVS TO YOUR REPOS

### ISSUE THREAD

**Issue by Qix-** [melizeche/comentaBOT#140]
PLEASE STOP adding famous developers to your repositories to get attention.

<img width="429" alt="screen shot 2016-02-03 at 17 03 21" src="https://cloud.githubusercontent.com/assets/885648/12801218/0d10ac8c-ca98-11e5-82df-8a593cbb886f.png">

It's super annoying and only craps up the notifications inbox of whom you add.

**Comment by ghost** [comment]
😂😂😂😂😂

**Comment by melizeche** [comment]
@Qix- My account was compromised, sorry for the inconviniences
